apiVersion: v1
kind: Service
metadata:
  name: seleniumapp-service
spec:
  selector:
    app: seleniumapp
  ports:
    - protocol:TCP
      port:80
      targetPort:5000
      nodePort:30011
  type: NodePort
  
